Add support for multiple ways to bind to the LDAP server.
pgadmin-org/pgadmin4 pull request #5374
Opened 2022-09-26 20:24 UTC by brunomgalmeida

The current format "{LDAP_USERNAME_ATTRIBUTE}={LDAP_USERNAME},{LDAP_BASE_DN}" does not work with scenarios where LDAP_USERNAME_ATTRIBUTE is for example 'sAMAccountName'

This "limitation" has been previously mentioned in https://github.com/pgadmin-org/pgadmin4/issues/3541

2022-09-27 04:52 UTC, adityatoshniwal requested changes
Otherwise, the changes looks good to me.

2022-09-27 04:52 UTC, adityatoshniwal commented on web/pgadmin/authenticate/ldap.py
> +            user_dn = config.LDAP_BIND_FORMAT.format (LDAP_USERNAME=self.username
Probably remove the space after `.format `

2022-09-27 09:02 UTC, akshay-joshi commented
Hi 

Please fix the Python style check as well.

2022-09-28 04:45 UTC, adityatoshniwal approved these changes

2022-09-28 05:17 UTC, merged