Password exec command
pgadmin-org/pgadmin4 pull request #5430
Opened 2022-10-12 17:10 UTC by aelgn

Generate a password externally by calling a shell command.

This will make working in pgAdmin with RDS IAM authentication viable, the passexec cmd will be executed on connect/reconnect if expired as configured under the Advanced tab in the Server dialog.

https://aws.amazon.com/premiumsupport/knowledge-center/rds-postgresql-connect-using-iam/

Example command
`aws --profile MyProfile rds generate-db-auth-token --hostname myhost.rds.amazonaws.com --port 5432 --region my-region --username my_user`

2022-10-13 10:30 UTC, adityatoshniwal requested changes
@aelgn Nice work there. Just a minor review mentioned below.
Also, please remove the changes for translation files as they're automatically generated before release.
Please update the screenshots as well - https://www.pgadmin.org/docs/pgadmin4/latest/server_dialog.html

2022-10-13 10:30 UTC, adityatoshniwal commented on web/pgadmin/browser/server_groups/servers/static/js/server.ui.js
> +          return !_.isUndefined(state.passexec_cmd) && !_.isNull(state.passexec_cmd);
simply use `!_.isEmpty(state.passexec_cmd)`

2022-10-13 16:51 UTC, aelgn commented
> @aelgn Nice work there. Just a minor review mentioned below. Also, please remove the changes for translation files as they're automatically generated before release. Please update the screenshots as well - https://www.pgadmin.org/docs/pgadmin4/latest/server_dialog.html

Thanks. I've updated the PR as requested 👍

2022-10-15 04:09 UTC, akshay-joshi commented
Hi @aelgn 

Python style is failing can you please fix those?

2022-10-15 08:29 UTC, aelgn commented
@akshay-joshi sure, lint is removed. Not so sure that I agree it looks better, but hey - I'm not here to change the rules ;)

2022-10-15 09:19 UTC, merged