Shared storage mount implementation in server mode #5014
pgadmin-org/pgadmin4 pull request #5911
Opened 2023-03-03 04:31 UTC by nikhil-mohite

2023-03-03 12:06 UTC, akshay-joshi requested changes

2023-03-06 10:38 UTC, nikhil-mohite commented on web/pgadmin/misc/file_manager/__init__.py
> +                        "you are not allow to {0}.".format(mode)))
Updated the error msg

2023-03-06 10:39 UTC, nikhil-mohite commented on web/pgadmin/misc/file_manager/__init__.py
> +                'ss': data['ss'],
updated variable name and all its occurrences

2023-03-06 10:40 UTC, nikhil-mohite commented on web/pgadmin/browser/__init__.py
> +        shared_storage_list = [sdir['name'] for sdir in config.SHARED_STORAGE]
Added extra logic to check the config provided by user is valid or not

2023-03-06 10:43 UTC, nikhil-mohite commented on web/config.py
> +# [{name: 'Shared 1', path: '/shared_folder', restricted_access: True/False}]
Done

2023-03-06 11:33 UTC, merged