Allow pgAdmin to retrive master password from external script.#4769
pgadmin-org/pgadmin4 pull request #6319
Opened 2023-05-24 08:15 UTC by yogeshmahajan-1903

2023-05-24 12:57 UTC, akshay-joshi requested changes

2023-05-25 07:02 UTC, yogeshmahajan-1903 commented on web/config.py
> +# E.g. - MASTER_PASSWORD_HOOK = '<PATH>/passwdgen.sh %u'
Done

2023-05-25 07:02 UTC, yogeshmahajan-1903 commented on web/pgadmin/browser/__init__.py
> +    # only when auth sources are oauth, kerberos, webserver.
Done

2023-05-25 07:03 UTC, yogeshmahajan-1903 commented on web/pgadmin/browser/__init__.py
> +        # master password(present) from user but no option to reset(existing).
Done

2023-05-25 07:03 UTC, yogeshmahajan-1903 commented on web/pgadmin/browser/__init__.py
> +    # & update data. If There is error while retrieving return with error
Done

2023-05-25 07:03 UTC, yogeshmahajan-1903 commented on web/pgadmin/browser/__init__.py
> +    # password in case of MASTER_PASSWORD_HOOK
Done

2023-05-25 08:19 UTC, merged