Fix an issue where queries longer than 1 minute get stuck - Container 7.1.  #6317
pgadmin-org/pgadmin4 pull request #6491
Opened 2023-06-23 12:09 UTC by khushboovashi

Fix an issue where queries get stuck with auto-completion enabled. #6356 
Fix an issue where queries can't complete execution. #6163

2023-06-25 18:57 UTC, nikhil-mohite requested changes

2023-06-25 18:57 UTC, nikhil-mohite commented on web/pgadmin/tools/sqleditor/utils/start_running_query.py
> +            if connect and not conn1.connected():
`conn1` variable is not defined

2023-06-26 11:02 UTC, nikhil-mohite approved these changes

2023-06-26 11:21 UTC, akshay-joshi requested changes

2023-06-26 11:21 UTC, akshay-joshi commented on docs/en_US/release_notes_7_4.rst
> +  | `Issue #6163 <https://github.com/pgadmin-org/pgadmin4/issues/6163>`_ -  Fix an issue where queries can't complete execution.
Please rearrange this in sorted order.

2023-07-04 05:14 UTC, merged