Added support to select/deselect objects in server backup #642
pgadmin-org/pgadmin4 pull request #6739
Opened 2023-09-06 05:14 UTC by nikhil-mohite

2023-09-07 11:07 UTC, adityatoshniwal requested changes

2023-09-07 11:07 UTC, adityatoshniwal commented on web/pgadmin/static/js/TreeView/index.jsx
> +function FolderArrow({ node, tree }) {
I would rather name it as `CollectionArrow`

2023-09-07 11:07 UTC, adityatoshniwal commented on web/pgadmin/static/js/TreeView/index.jsx
> +      {node.isInternal ? (
do not use nested ternary, it will upset sonarqube and difficult to read as well.

2023-09-07 11:07 UTC, adityatoshniwal commented on web/pgadmin/tools/backup/static/js/backup.js
> +          let endpoint = 'backup.objects';
there is no need for the `endpoint` var. check other places.

2023-09-07 11:07 UTC, adityatoshniwal commented on web/pgadmin/tools/backup/static/js/backup.ui.js
> +        state.objects = selectedNodeCollection;
don't set `state` directly. use `return {objects: selectedNodeCollection}`

2023-09-07 11:07 UTC, adityatoshniwal commented on web/regression/javascript/schema_ui_files/backup.ui.spec.js
> +// import MockAdapter from 'axios-mock-adapter';
remove commented code.

2023-09-08 10:59 UTC, akshay-joshi requested changes
1) Materialized View is not visible in the tree.
2) The Foreign Table is not visible in the tree.
3) As per the discussion Schema selection should have three states:     
     a) Fully selected then the "--schema" command will run.
     b) Partially selected means all the children selected then the command for all the selected objects should be run.
     c) Not selected, not all the children are selected. 
4) In case there are no objects to show in the Objects tab, there should be a message "No objects are found to display" or something like that.

5) Can we add View, MView, Sequences, and Foreign Table in the supported node? Check the feasibility. 
   backupSupportedNodes = [ 'database', 'schema', 'table', 'partition']

6) A backend error comes when selecting any table and clicking on Backup and selecting the Objects tab.

2023-09-08 10:59 UTC, akshay-joshi commented on docs/en_US/backup_dialog.rst
> +    * If selected schema then it will take backup of that selected schema only.
If Schema is selected then it will take the backup of that selected schema only.

2023-09-08 10:59 UTC, akshay-joshi commented on docs/en_US/backup_dialog.rst
> +    * If selected Table, View, Sequences, Foreign Table it will take backup of selected objects only.
If any Table, View, Materialized View, Sequences, or Foreign Table is selected then it will take the backup of those selected objects.

2023-09-11 13:23 UTC, nikhil-mohite commented
> 5\. Can we add View, MView, Sequences, and Foreign Table in the supported node? Check the feasibility.
>     backupSupportedNodes = [ 'database', 'schema', 'table', 'partition']

Resolved all the review comments (Point 5th is not added in this commit)

2023-09-12 07:41 UTC, adityatoshniwal requested changes

2023-09-12 07:41 UTC, adityatoshniwal commented on web/pgadmin/static/js/PgTreeView/index.jsx
> +export const TreeEventContext = React.createContext();
this doesn't look to be used anywhere.

2023-09-12 07:41 UTC, adityatoshniwal commented on web/pgadmin/static/js/PgTreeView/index.jsx
> +function TreeView({data, treeRef, eventBusObj, onSelectionChange, hasCheckbox=false}){
please merge this with the PgTreeView. No need to separate this.

2023-09-12 07:41 UTC, adityatoshniwal commented on web/pgadmin/static/js/PgTreeView/index.jsx
> +      chNode.parent.data.is_indeterminate = true;
Can we use `isIndeterminate` casing?

2023-09-13 05:37 UTC, merged