Fixed UI issues
pgadmin-org/pgadmin4 pull request #6833
Opened 2023-10-05 20:36 UTC by Sahil1479

- Resolved following UI related issues.

![image](https://github.com/pgadmin-org/pgadmin4/assets/56965873/1f863a70-fc33-4e8c-85bb-30dbd88e222e)
- Added label (in header) to the table for Memory and CPU tabs.

2023-10-06 06:01 UTC, khushboovashi requested changes

2023-10-06 06:01 UTC, khushboovashi commented on web/pgadmin/dashboard/static/js/SystemStats/Storage.jsx
> +                {
```suggestion
                {
```

2023-10-06 06:01 UTC, khushboovashi commented on web/pgadmin/static/js/components/PgChart/StreamingChart.jsx
> +
```suggestion
 
```

2023-10-06 21:52 UTC, Sahil1479 commented
@khushboovashi As suggested, I've removed the trailing white spaces.

2023-10-09 12:29 UTC, khushboovashi commented
> This branch is out-of-date with the base branch

Please rebase your branch, so I can merge the changes.

2023-10-10 06:40 UTC, akshay-joshi commented
@Sahil1479 

Can you please rebase the branch and close all the conversations asap?

2023-10-10 07:01 UTC, Sahil1479 commented
Hi @khushboovashi and @akshay-joshi, actually I'm out of station and don't have laptop with me. I'll do it by EOD. Is that fine?

2023-10-10 07:06 UTC, akshay-joshi commented
> Hi @khushboovashi and @akshay-joshi, actually I'm out of station and don't have laptop with me. I'll do it by EOD. Is that fine?

Yes, no problem

2023-10-10 18:26 UTC, Sahil1479 commented
@khushboovashi, @akshay-joshi Rebased the branch and closed all the conversations.

2023-10-11 05:57 UTC, merged