Added the ability to convert the View/Edit Data tab into the Query Tool tab #5908
pgadmin-org/pgadmin4 pull request #7030
Opened 2023-12-04 09:56 UTC by nikhil-mohite

2023-12-05 12:36 UTC, adityatoshniwal commented
Press backspace and cancel promotion. The query will apply the backspace. I think it should show the cursor but CM should be readonly.

<img width="1791" alt="image" src="https://github.com/pgadmin-org/pgadmin4/assets/31855755/909ff069-7621-45a4-b910-0412abcfa1d1">

2023-12-05 12:37 UTC, adityatoshniwal requested changes

2023-12-05 12:37 UTC, adityatoshniwal commented on web/pgadmin/tools/sqleditor/static/js/components/sections/Query.jsx
> +          setIsPromoted((prev)=> {
there is no need to maintain state for ispromoted. You can do the keydown unbind there itself.

2023-12-05 12:37 UTC, adityatoshniwal commented on web/pgadmin/tools/sqleditor/utils/query_tool_preferences.py
> +        gettext("Show View/Edit Data Promotion Warning ?"),
remove the space before question mark.

2023-12-05 12:37 UTC, adityatoshniwal commented on web/pgadmin/tools/sqleditor/utils/query_tool_preferences.py
> +            'If set to True, View/Edit Data window will show promote '
If set to True, View/Edit Data tool will show promote to Query tool confirm dialog on query edit.

2023-12-05 12:38 UTC, adityatoshniwal commented
On backspace and continue - it adds "Backspace"

2023-12-18 09:25 UTC, nikhil-mohite commented
> Shouldn't we also update the titles and remove the table name? FYI, all the feature tests are failing for this.

Done

2023-12-18 09:26 UTC, nikhil-mohite commented
> On backspace and continue - it adds "Backspace" <img alt="image" width="848" src="https://private-user-images.githubusercontent.com/31855755/288040564-69109c4b-2f21-441c-b3b1-19394cc8e412.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4OTE4MzEsIm5iZiI6MTcwMjg5MTUzMSwicGF0aCI6Ii8zMTg1NTc1NS8yODgwNDA1NjQtNjkxMDljNGItMmYyMS00NDFjLWIzYjEtMTkzOTRjYzhlNDEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDA5MjUzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0MTZmMDgyOGUxNmEzN2QzZGFiMjhiYWJjZDMwOGQxYWIxNTI2Zjc3OTUzZWFiNzM1ZTkyNmFjNmNkMDYxMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tQoRakLl4gTfzMR4SEipFOUawYeAejGWtVt1nq_GTbw">

Resolved

2023-12-18 12:24 UTC, nikhil-mohite commented
> The pop-up appears for literally any key. I tried with simple CMD+Tab or capslock. Otherwise, looks to be working fine.
  
Will check if we can avoid this.

2023-12-18 12:46 UTC, adityatoshniwal commented
> > The pop-up appears for literally any key. I tried with simple CMD+Tab or capslock. Otherwise, looks to be working fine.
> 
> Will check if we can avoid this.

The logic I suggest can be - listen the CodeMirror onchange event and based on that show the pop-up. I guess you'll have to keep it editable.

2023-12-19 08:44 UTC, nikhil-mohite commented
> > > The pop-up appears for literally any key. I tried with simple CMD+Tab or capslock. Otherwise, looks to be working fine.
> > 
> > 
> > Will check if we can avoid this.
> 
> The logic I suggest can be - listen the CodeMirror onchange event and based on that show the pop-up. I guess you'll have to keep it editable.

Done

2023-12-19 10:22 UTC, merged