Add --yes option to delete user via CLI for scripting purpose
pgadmin-org/pgadmin4 pull request #7190
Opened 2024-02-06 13:52 UTC by octo-dama

# Purpose

For scripting purpose, I would like to be able to delete users via CLI without the confirmation prompt.

# Changes

- Added --yes option to delete_user CLI options

2024-02-09 10:03 UTC, jonapoirier commented
Such a nice feature !

2024-02-12 06:06 UTC, khushboovashi requested changes
The changes look good to me; however, the doc update needs to be included.
Please add this option to the user_management.rst file under the appropriate head.

2024-02-12 11:04 UTC, khushboovashi requested changes

2024-02-12 11:04 UTC, khushboovashi commented on web/setup.py
> +                    auto_confirm: Annotated[Optional[bool],
Please fix the PEP-8 issue. Check https://github.com/pgadmin-org/pgadmin4/actions/runs/7868821161/job/21470109856?pr=7190 for the same.

2024-02-14 05:50 UTC, merged