Added support for provider,deterministic,version and RULES parameter while creating collation. #5611
pgadmin-org/pgadmin4 pull request #7247
Opened 2024-02-28 10:08 UTC by JyotiEdb

2024-02-28 10:19 UTC, adityatoshniwal requested changes

2024-02-28 10:19 UTC, adityatoshniwal commented on web/pgadmin/browser/server_groups/servers/databases/schemas/collations/static/js/collation.ui.js
> +    if (isEmptyString(state.version)){
Why is version mandatory? It is optional in docs - https://www.postgresql.org/docs/current/sql-createcollation.html.

2024-02-28 10:19 UTC, adityatoshniwal commented on web/pgadmin/browser/server_groups/servers/databases/schemas/collations/static/js/collation.ui.js
> +      {
Just like localle, LC_COLLATE - these new fields should also be disabled when using "copy from" as they're not applicable. Check the docs - https://www.postgresql.org/docs/current/sql-createcollation.html

2024-02-28 10:19 UTC, adityatoshniwal commented on web/pgadmin/browser/server_groups/servers/databases/schemas/collations/__init__.py
> -
Not sure why you've removed this blank lines everywhere but those were added for readability reasons. Check your patch once again.

2024-02-28 10:20 UTC, adityatoshniwal requested changes
Fix the failing tests also.

2024-03-18 11:05 UTC, adityatoshniwal requested changes

2024-03-18 11:05 UTC, adityatoshniwal commented on web/pgadmin/browser/server_groups/servers/databases/schemas/collations/__init__.py
> +        node = self.blueprint.generate_browser_node(
why was this changed?

2024-03-18 11:05 UTC, adityatoshniwal commented on web/pgadmin/browser/server_groups/servers/databases/schemas/collations/static/js/collation.ui.js
> +        readonly: function (state) { return !obj.isNew(state); },
if the mode is only properties then it will always be readonly.

2024-03-18 11:05 UTC, adityatoshniwal commented on web/pgadmin/browser/server_groups/servers/databases/schemas/collations/tests/pg/16_plus/alter_collation.sql
> +    OWNER TO postgres;
why is this changed? I think it is required for epas servers. Did you run tests on epas?

2024-03-18 11:05 UTC, adityatoshniwal commented on web/pgadmin/browser/server_groups/servers/databases/schemas/collations/tests/pg/16_plus/create_collation.sql
> +    OWNER TO postgres;
same as above

2024-03-19 09:58 UTC, gaval1github requested changes
Minor change - Collation_sql.png should reflect what is entered in the dialog. So in short, don't update this screenshot.
Otherwise, code looks good to me.

2024-03-19 09:59 UTC, adityatoshniwal requested changes
Minor change - Collation_sql.png should reflect what is entered in the dialog. So in short, don't update this screenshot.
Otherwise, code looks good to me.

2024-03-19 10:47 UTC, adityatoshniwal approved these changes

2024-03-19 11:22 UTC, merged