Added support for viewing Log Based Clusters. #7216
pgadmin-org/pgadmin4 pull request #7287
Opened 2024-03-18 06:20 UTC by adityatoshniwal

2024-03-19 11:13 UTC, akshay-joshi requested changes
GUI related:
1) The Replication tab is not visible on registering the server. It is visible after reconnecting to the server.
2) The CREATE Script context menu should not be visible on the Replica Nodes.
3) Set the Replication tab in the focus and select any other database server from the Object Explorer. The tab is removed but the contents of the tab are still visible.
4) Replication tab add 'Reply time' in the Replication stats table and add 'Active PID' in the Replication Slots table. Can we remove 'Slot Type'?

Code related:
1) Remove the pg folder from "replica_nodes -> pg -> sql ->" as it should work for EPAS.
2) Documentation is missing.

2024-03-19 11:13 UTC, akshay-joshi commented on web/pgadmin/dashboard/static/js/Replication/index.jsx
> +import { getSwitchCell } from '../../../../static/js/components/PgTable';
import { getExpandCell } from '../../../../static/js/components/PgTable';
import { getSwitchCell } from '../../../../static/js/components/PgTable';

Combine the import statements

2024-03-19 11:13 UTC, akshay-joshi commented on web/pgadmin/dashboard/static/js/components/RefreshButtons.jsx
Add Copyright header

2024-03-19 12:03 UTC, adityatoshniwal commented on web/pgadmin/browser/server_groups/servers/replica_nodes/static/img/coll-replica_nodes.svg
The icon is going to be changed. That's why I created a copy for now.

2024-03-19 12:03 UTC, adityatoshniwal commented on web/pgadmin/browser/server_groups/servers/replica_nodes/static/img/replica_nodes.svg
The icon is going to be changed. That's why I created a copy for now.

2024-03-19 12:04 UTC, adityatoshniwal commented on web/pgadmin/browser/server_groups/servers/replica_nodes/__init__.py
> +        self.server_type = ['pg', 'ppas']
I'm not sure. I just copied existing.

2024-03-19 12:05 UTC, adityatoshniwal commented on web/pgadmin/browser/server_groups/servers/replica_nodes/__init__.py
> +class ReplicationNodesView(NodeView):
I copied from tablespace. Need to check.

2024-03-19 12:07 UTC, adityatoshniwal commented on web/pgadmin/browser/server_groups/servers/replica_nodes/__init__.py
> +                self.manager.server_type, self.manager.version)
Currently it is required since we have server type in path. Once base path is changed, it can be removed.

2024-03-20 06:57 UTC, akshay-joshi requested changes
Still the following issues are not fixed:

- The Replication tab is not visible on registering the server. It is visible after reconnecting to the server.
- The CREATE Script context menu should not be visible on the Replica Nodes.
- Documentation missing.

2024-03-20 06:57 UTC, akshay-joshi commented on web/pgadmin/browser/server_groups/servers/replica_nodes/__init__.py
> +        'nodes': [{'get': 'node'}, {'get': 'nodes'}],
{'get': 'node'} it is still there.

2024-03-28 06:45 UTC, akshay-joshi approved these changes

2024-03-28 06:49 UTC, merged