Update MUI5 Library.
pgadmin-org/pgadmin4 pull request #7313
Opened 2024-03-25 10:37 UTC by yogeshmahajan-1903

Remove scss files and its references from multiple modules. Remove scss bundling in webpacker.
Update Datefns,Dateio.Removed popper.js,sass-loader.

2024-03-28 12:42 UTC, adityatoshniwal requested changes
I've committed some changes related to webpack for more cleanup(It might fix some issues). Below are other issues I found.
<img width="1728" alt="Screenshot 2024-03-28 at 12 58 25" src="https://github.com/pgadmin-org/pgadmin4/assets/31855755/fefe1ba5-3f6b-48db-bb50-44c7cd1cd3cb">
<img width="914" alt="Screenshot 2024-03-28 at 13 00 23" src="https://github.com/pgadmin-org/pgadmin4/assets/31855755/6977d4da-2d92-4f40-8db8-113656562489">
<img width="774" alt="Server Configuration" src="https://github.com/pgadmin-org/pgadmin4/assets/31855755/60e68092-b87f-4b2f-87db-30ac4b160ea8">
<img width="204" alt="The underline color" src="https://github.com/pgadmin-org/pgadmin4/assets/31855755/3d60dfaf-5cb4-499a-8156-3df29bb547ef">
<img width="381" alt="General Definition Security" src="https://github.com/pgadmin-org/pgadmin4/assets/31855755/75c267ee-b0bd-4f95-aa56-6d6f4d0dc33d">

2024-03-28 12:42 UTC, adityatoshniwal commented on web/pgadmin/static/js/components/Buttons.jsx
> +      //padding: '1px 4px'
remove commented.

2024-03-28 12:42 UTC, adityatoshniwal commented on web/pgadmin/static/js/components/Buttons.jsx
> +    backgroundColor: '#00000000',
removed transparent?

2024-03-28 12:42 UTC, adityatoshniwal commented on web/pgadmin/templates/base.html
> +    :root {
this should not be hard coded. It should be set based on theme.

2024-03-28 12:42 UTC, adityatoshniwal commented on web/pgadmin/templates/base.html
> +  -webkit-box-shadow: 0 0 0px 1000px #d6effc inset;
even this should be based on theme.

2024-03-28 12:42 UTC, adityatoshniwal commented on web/pgadmin/tools/schema_diff/static/js/components/SchemaDiffButtonComponent.jsx
> +          <PgIconButton title={isDisableCompare? '':gettext('Compare')} icon={<KeyboardArrowDownIcon />} color={'primary'} splitButton
why is this change needed.

2024-03-28 12:42 UTC, adityatoshniwal commented on web/regression/feature_tests/keyboard_shortcut_test.py
> +        # maximize_button.click()
can remove commented code.

2024-03-28 12:42 UTC, adityatoshniwal commented on web/regression/feature_utils/pgadmin_page.py
> +                #     "div.dock-tab-btn[id$='id-query']").click()
cann remove commented code.

2024-03-29 04:27 UTC, yogeshmahajan-1903 commented on web/regression/feature_utils/pgadmin_page.py
> +                #     "div.dock-tab-btn[id$='id-query']").click()
Done

2024-03-29 04:27 UTC, yogeshmahajan-1903 commented on web/regression/feature_tests/keyboard_shortcut_test.py
> +        # maximize_button.click()
Done

2024-03-29 04:29 UTC, yogeshmahajan-1903 commented on web/pgadmin/static/js/components/Buttons.jsx
> +      //padding: '1px 4px'
Done

2024-03-29 04:30 UTC, yogeshmahajan-1903 commented on web/pgadmin/static/js/Theme/overrides/pgadmin.classes.override.js
> +
Done

2024-03-29 04:32 UTC, yogeshmahajan-1903 commented on web/pgadmin/browser/__init__.py
> +    theme = theme_path_pref.get()
Done

2024-03-29 04:32 UTC, yogeshmahajan-1903 commented on web/pgadmin/misc/themes/__init__.py
> +    # )
Done

2024-03-29 04:35 UTC, yogeshmahajan-1903 commented on web/pgadmin/authenticate/oauth2.py
> +        current_app.logger.exception(profile)
Yes. Done

2024-03-29 05:06 UTC, yogeshmahajan-1903 commented on web/package.json
> +    "@types/react": "^18.2.56",
Done

2024-03-29 07:50 UTC, yogeshmahajan-1903 commented on web/pgadmin/templates/base.html
> +  -webkit-box-shadow: 0 0 0px 1000px #d6effc inset;
Done.

2024-03-29 07:54 UTC, yogeshmahajan-1903 commented on web/pgadmin/static/js/Theme/high_contrast.js
> +        treeTextFg: '#ffffff',
Done.

2024-03-29 10:54 UTC, yogeshmahajan-1903 commented on web/pgadmin/static/js/components/Buttons.jsx
> +    backgroundColor: '#00000000',
Done

2024-04-01 05:52 UTC, yogeshmahajan-1903 commented on web/pgadmin/misc/themes/__init__.py
> +            "cssfile": "pgadmin.theme.dark",
Done

2024-04-01 05:52 UTC, yogeshmahajan-1903 commented on web/pgadmin/static/bundle/app.js
> +    <Theme theme={theme}>
Done.

2024-04-01 05:52 UTC, yogeshmahajan-1903 commented on web/pgadmin/tools/schema_diff/static/js/components/SchemaDiffButtonComponent.jsx
> +          <PgIconButton title={isDisableCompare? '':gettext('Compare')} icon={<KeyboardArrowDownIcon />} color={'primary'} splitButton
Done

2024-04-01 05:53 UTC, yogeshmahajan-1903 commented on web/pgadmin/static/bundle/app.js
> +  initializeModules(pgAdmin.Preferences);
This is required to fetch theme data for first time.

2024-04-01 06:02 UTC, adityatoshniwal commented on web/pgadmin/static/bundle/app.js
> +  initializeModules(pgAdmin.Preferences);
But you're using pgAdmin.utils for initial theme info.

2024-04-01 10:46 UTC, yogeshmahajan-1903 commented on web/pgadmin/static/js/Theme/overrides/reactaspen.override.js
> +          background: '#da2d38',
Done

2024-04-09 02:51 UTC, merged