fixed typos
pgadmin-org/pgadmin4 pull request #7483
Opened 2024-05-17 10:31 UTC by Ahmad495

2024-05-17 11:25 UTC, akshay-joshi commented
@Ahmad495 

No need to change the *.po file. Please update the PR and make changes only to the source code files

2024-05-19 11:58 UTC, Ahmad495 commented
> @Ahmad495
> 
> No need to change the *.po file. Please update the PR and make changes only to the source code files

removed the changes made to .po files.

2024-05-20 06:26 UTC, akshay-joshi requested changes

2024-05-20 06:26 UTC, akshay-joshi commented on web/pgadmin/authenticate/mfa/views.py
> +    An internal utility function to execute mfa.validate(...) method in case, it
Fixed the PEP8 issue as this line is more than 80 columns.

2024-05-23 05:49 UTC, akshay-joshi commented
@Ahmad495 

Could you please fix this and send the PR today? I'll generate the .po file and commit it for the translations.

2024-05-23 06:20 UTC, Ahmad495 commented
> @Ahmad495
> 
> Could you please fix this and update the PR today? I'll generate the .po file and commit it for the translations.

Fixed PEP8 issue.

2024-05-23 07:22 UTC, merged