Fix Usability issue with Macros and add new feature to Macros (RM #6969) #4735
pgadmin-org/pgadmin4 pull request #7496
Opened 2024-05-21 15:00 UTC by RohitBhati8269

More Details :- [task-link](https://github.com/pgadmin-org/pgadmin4/issues/4735)

2024-05-23 07:46 UTC, akshay-joshi requested changes
1. If key binding is not there, then no need to display empty brackets.
2. When you add a new row focus should be on SQL control.
3. Default macro names should be picked using the id of the macros table.

2024-05-23 07:46 UTC, akshay-joshi commented on web/pgadmin/model/__init__.py
> +    key_code = db.Column(db.Integer, nullable=True)
This change is not required.

2024-05-23 07:46 UTC, akshay-joshi commented on web/pgadmin/tools/sqleditor/__init__.py
> +    This method is used to get all the columns for data sorting dialog.
Correct the function comment. Seems copy paste error.

2024-05-23 07:46 UTC, akshay-joshi commented on web/pgadmin/tools/sqleditor/static/js/components/dialogs/MacrosDialog.jsx
> +
A similar function is defined in the QueryToolComponent.jsx. Please make a common function and use it.

2024-05-24 07:14 UTC, RohitBhati8269 commented
> * When you add a new row focus should be on SQL control.

@akshay-joshi  As just this one is not updated as per our discussion on scrum.

2024-05-24 09:47 UTC, akshay-joshi requested changes

2024-05-24 09:47 UTC, akshay-joshi commented on web/pgadmin/model/__init__.py
> +    key_code = db.Column(db.Integer)
Revert this to the original logic. No changes needed.

2024-05-24 10:00 UTC, merged