Added a menu option to close all server and database connections. #1984
pgadmin-org/pgadmin4 pull request #8080
Opened 2024-11-04 07:59 UTC by pravesh-sharma

2024-11-05 12:24 UTC, anilsahoo20 reviewed
1. After multiple database connections opened, if I click on `Disconnect from all databases` menu option, it disconnects all the databases but the Menu option must be deactivated, but currently it is still active.
2. After clicking the `Disconnect from all servers`, the focus on Servers group is going away. 
3. After clicking the `Disconnect from all servers`, if we see the object menu, it show many options and we click on any of the option, it is not working.

2024-11-05 12:29 UTC, pravesh-sharma commented
> 1. After multiple database connections opened, if I click on `Disconnect from all databases` menu option, it disconnects all the databases but the Menu option must be deactivated, but currently it is still active.
> 2. After clicking the `Disconnect from all servers`, the focus on Servers group is going away.
> 3. After clicking the `Disconnect from all servers`, if we see the context menu, it show many options and we click on any of the option, it is not working.

#2 is expected behaviour.

2024-11-06 05:35 UTC, adityatoshniwal requested changes

2024-11-06 10:13 UTC, anilsahoo20 approved these changes

2024-11-06 10:22 UTC, merged